import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface Translations {
  [key: string]: {
    fr: string;
    en: string;
  };
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations: Translations = {
  // ==================== GENERAL ====================
  'app.name': { fr: 'Saddle Point Service', en: 'Saddle Point Service' },
  'app.slogan': { fr: 'Excellence en Solutions Électriques', en: 'Excellence in Electrical Solutions' },
  'loading': { fr: 'Chargement...', en: 'Loading...' },
  'welcome': { fr: 'Bienvenue', en: 'Welcome' },
  'yes': { fr: 'Oui', en: 'Yes' },
  'no': { fr: 'Non', en: 'No' },
  'or': { fr: 'ou', en: 'or' },
  'and': { fr: 'et', en: 'and' },
  'all': { fr: 'Tous', en: 'All' },
  'none': { fr: 'Aucun', en: 'None' },
  'active': { fr: 'Actif', en: 'Active' },
  'inactive': { fr: 'Inactif', en: 'Inactive' },
  'headquarters': { fr: 'Siège', en: 'Headquarters' },
  'total': { fr: 'Total', en: 'Total' },

  // ==================== NAVIGATION ====================
  'nav.home': { fr: 'Accueil', en: 'Home' },
  'nav.dashboard': { fr: 'Tableau de Bord', en: 'Dashboard' },
  'nav.articles': { fr: 'Articles', en: 'Articles' },
  'nav.services': { fr: 'Services', en: 'Services' },
  'nav.sales': { fr: 'Ventes', en: 'Sales' },
  'nav.stock': { fr: 'Stock', en: 'Stock' },
  'nav.clients': { fr: 'Clients', en: 'Clients' },
  'nav.reports': { fr: 'Rapports', en: 'Reports' },
  'nav.settings': { fr: 'Paramètres', en: 'Settings' },
  'nav.suppliers': { fr: 'Fournisseurs', en: 'Suppliers' },
  'nav.logout': { fr: 'Déconnexion', en: 'Logout' },
  'nav.accounting': { fr: 'Comptabilité', en: 'Accounting' },
  'nav.stores': { fr: 'Boutiques', en: 'Stores' },
  'nav.users': { fr: 'Utilisateurs', en: 'Users' },
  'nav.profile': { fr: 'Profil', en: 'Profile' },
  'nav.categories': { fr: 'Catégories', en: 'Categories' },
  'nav.locations': { fr: 'Points de Vente', en: 'Locations' },

  // ==================== AUTH ====================
  'auth.login': { fr: 'Connexion', en: 'Login' },
  'auth.email': { fr: 'Email', en: 'Email' },
  'auth.password': { fr: 'Mot de passe', en: 'Password' },
  'auth.signin': { fr: 'Se connecter', en: 'Sign In' },
  'auth.signout': { fr: 'Déconnexion', en: 'Sign Out' },
  'auth.welcome': { fr: 'Bienvenue', en: 'Welcome' },
  'auth.enterEmail': { fr: 'Veuillez entrer votre email', en: 'Please enter your email' },
  'auth.invalidEmail': { fr: 'Veuillez entrer un email valide', en: 'Please enter a valid email' },
  'auth.enterPassword': { fr: 'Veuillez entrer votre mot de passe', en: 'Please enter your password' },
  'auth.passwordMin': { fr: 'Le mot de passe doit contenir au moins 6 caractères', en: 'Password must be at least 6 characters' },
  'auth.invalidCredentials': { fr: 'Email ou mot de passe incorrect', en: 'Invalid email or password' },
  'auth.error': { fr: 'Une erreur est survenue. Veuillez réessayer.', en: 'An error occurred. Please try again.' },
  'auth.closeModal': { fr: 'Fermer la fenêtre de connexion', en: 'Close login window' },
  'auth.contactAdmin': { fr: 'Contactez l\'administrateur si vous avez oublié vos identifiants.', en: 'Contact the administrator if you forgot your credentials.' },
  'auth.rememberMe': { fr: 'Se souvenir de moi', en: 'Remember me' },
  'auth.forgotPassword': { fr: 'Mot de passe oublié ?', en: 'Forgot password?' },
  'auth.guest': { fr: 'Invité', en: 'Guest' },
  'auth.register': { fr: 'S\'inscrire', en: 'Sign up' },
  'auth.registration': { fr: 'Inscription Client', en: 'Client Registration' },
  'auth.createAccount': { fr: 'Créer un compte', en: 'Create an account' },
  'auth.alreadyHaveAccount': { fr: 'Vous avez déjà un compte ?', en: 'Already have an account?' },
  'auth.noAccount': { fr: 'Pas encore de compte ?', en: 'Don\'t have an account?' },
  'auth.signupSuccess': { fr: 'Compte créé avec succès ! Vous pouvez maintenant vous connecter.', en: 'Account created successfully! You can now login.' },
  'auth.signupError': { fr: 'Erreur lors de la création du compte.', en: 'Error creating account.' },
  'auth.name': { fr: 'Nom complet', en: 'Full name' },
  'auth.phone': { fr: 'Téléphone', en: 'Phone' },
  'auth.address': { fr: 'Adresse', en: 'Address' },
  'auth.confirmPassword': { fr: 'Confirmer le mot de passe', en: 'Confirm password' },
  'auth.passwordMismatch': { fr: 'Les mots de passe ne correspondent pas', en: 'Passwords do not match' },
  'auth.registerAsClient': { fr: 'Inscription en tant que client', en: 'Register as client' },

  // ==================== ORDERS ====================
  'orders.title': { fr: 'Mes Commandes', en: 'My Orders' },
  'orders.trackOrders': { fr: 'Suivez l\'\u00e9tat de vos commandes', en: 'Track your orders status' },
  'orders.totalOrders': { fr: 'Total Commandes', en: 'Total Orders' },
  'orders.totalAmount': { fr: 'Montant Total', en: 'Total Amount' },
  'orders.pending': { fr: 'En attente', en: 'Pending' },
  'orders.confirmed': { fr: 'Confirm\u00e9e', en: 'Confirmed' },
  'orders.preparing': { fr: 'En pr\u00e9paration', en: 'Preparing' },
  'orders.shipped': { fr: 'Exp\u00e9di\u00e9e', en: 'Shipped' },
  'orders.delivered': { fr: 'Livr\u00e9e', en: 'Delivered' },
  'orders.cancelled': { fr: 'Annul\u00e9e', en: 'Cancelled' },
  'orders.searchPlaceholder': { fr: 'Rechercher par num\u00e9ro de commande ou article...', en: 'Search by order number or item...' },
  'orders.allStatuses': { fr: 'Tous les statuts', en: 'All statuses' },
  'orders.noOrders': { fr: 'Vous n\'avez pas encore de commande', en: 'You have no orders yet' },
  'orders.noMatch': { fr: 'Aucune commande ne correspond \u00e0 vos crit\u00e8res', en: 'No orders match your criteria' },
  'orders.viewDetails': { fr: 'Voir d\u00e9tails', en: 'View details' },
  'orders.orderDetails': { fr: 'D\u00e9tails de la commande', en: 'Order details' },
  'orders.orderDate': { fr: 'Date de commande', en: 'Order date' },
  'orders.orderNumber': { fr: 'Num\u00e9ro de commande', en: 'Order number' },
  'orders.items': { fr: 'Articles command\u00e9s', en: 'Ordered items' },
  'orders.quantity': { fr: 'Quantit\u00e9', en: 'Quantity' },
  'orders.status': { fr: 'Statut', en: 'Status' },
  'orders.article': { fr: 'article', en: 'item' },
  'orders.articles': { fr: 'articles', en: 'items' },

  // ==================== ACTIONS ====================
  'action.save': { fr: 'Enregistrer', en: 'Save' },
  'action.cancel': { fr: 'Annuler', en: 'Cancel' },
  'action.confirm': { fr: 'Confirmer', en: 'Confirm' },
  'action.delete': { fr: 'Supprimer', en: 'Delete' },
  'action.edit': { fr: 'Modifier', en: 'Edit' },
  'action.add': { fr: 'Ajouter', en: 'Add' },
  'action.create': { fr: 'Créer', en: 'Create' },
  'action.update': { fr: 'Mettre à jour', en: 'Update' },
  'action.view': { fr: 'Voir', en: 'View' },
  'action.search': { fr: 'Rechercher', en: 'Search' },
  'action.filter': { fr: 'Filtrer', en: 'Filter' },
  'action.export': { fr: 'Exporter', en: 'Export' },
  'action.exportPdf': { fr: 'Exporter PDF', en: 'Export PDF' },
  'action.exportExcel': { fr: 'Exporter Excel', en: 'Export Excel' },
  'action.import': { fr: 'Importer', en: 'Import' },
  'action.importExcel': { fr: 'Importer Excel', en: 'Import Excel' },
  'action.print': { fr: 'Imprimer', en: 'Print' },
  'action.download': { fr: 'Télécharger', en: 'Download' },
  'action.close': { fr: 'Fermer', en: 'Close' },
  'action.back': { fr: 'Retour', en: 'Back' },
  'action.next': { fr: 'Suivant', en: 'Next' },
  'action.previous': { fr: 'Précédent', en: 'Previous' },
  'action.refresh': { fr: 'Actualiser', en: 'Refresh' },
  'action.reset': { fr: 'Réinitialiser', en: 'Reset' },
  'action.apply': { fr: 'Appliquer', en: 'Apply' },
  'action.clear': { fr: 'Effacer', en: 'Clear' },
  'action.select': { fr: 'Sélectionner', en: 'Select' },
  'action.selectAll': { fr: 'Tout sélectionner', en: 'Select all' },
  'action.markAllRead': { fr: 'Tout marquer comme lu', en: 'Mark all as read' },
  'action.addToCart': { fr: 'Ajouter au panier', en: 'Add to cart' },
  'action.backToList': { fr: 'Retour à la liste', en: 'Back to list' },
  'action.backToDashboard': { fr: 'Retour au tableau de bord', en: 'Back to dashboard' },
  'action.send': { fr: 'Envoyer', en: 'Send' },

  // ==================== COMMON LABELS ====================
  'label.name': { fr: 'Nom', en: 'Name' },
  'label.fullName': { fr: 'Nom complet', en: 'Full name' },
  'label.email': { fr: 'Email', en: 'Email' },
  'label.phone': { fr: 'Téléphone', en: 'Phone' },
  'label.address': { fr: 'Adresse', en: 'Address' },
  'label.city': { fr: 'Ville', en: 'City' },
  'label.country': { fr: 'Pays', en: 'Country' },
  'label.date': { fr: 'Date', en: 'Date' },
  'label.time': { fr: 'Heure', en: 'Time' },
  'label.dateTime': { fr: 'Date et Heure', en: 'Date and Time' },
  'label.description': { fr: 'Description', en: 'Description' },
  'label.category': { fr: 'Catégorie', en: 'Category' },
  'label.status': { fr: 'Statut', en: 'Status' },
  'label.type': { fr: 'Type', en: 'Type' },
  'label.price': { fr: 'Prix', en: 'Price' },
  'label.quantity': { fr: 'Quantité', en: 'Quantity' },
  'label.amount': { fr: 'Montant', en: 'Amount' },
  'label.reference': { fr: 'Référence', en: 'Reference' },
  'label.notes': { fr: 'Notes', en: 'Notes' },
  'label.color': { fr: 'Couleur', en: 'Color' },
  'label.image': { fr: 'Image', en: 'Image' },
  'label.role': { fr: 'Rôle', en: 'Role' },
  'label.permissions': { fr: 'Permissions', en: 'Permissions' },
  'label.actions': { fr: 'Actions', en: 'Actions' },
  'label.details': { fr: 'Détails', en: 'Details' },
  'label.summary': { fr: 'Résumé', en: 'Summary' },
  'label.total': { fr: 'Total', en: 'Total' },
  'label.subtotal': { fr: 'Sous-total', en: 'Subtotal' },
  'label.tax': { fr: 'TVA', en: 'Tax' },
  'label.discount': { fr: 'Remise', en: 'Discount' },
  'label.company': { fr: 'Entreprise', en: 'Company' },
  'label.manager': { fr: 'Responsable', en: 'Manager' },
  'label.createdAt': { fr: 'Créé le', en: 'Created at' },
  'label.updatedAt': { fr: 'Modifié le', en: 'Updated at' },
  'label.postalCode': { fr: 'Code postal', en: 'Postal code' },

  // ==================== PLACEHOLDERS ====================
  'placeholder.search': { fr: 'Rechercher...', en: 'Search...' },
  'placeholder.searchClient': { fr: 'Rechercher un client (nom, email, tel)...', en: 'Search client (name, email, phone)...' },
  'placeholder.searchArticle': { fr: 'Rechercher un article ou service...', en: 'Search article or service...' },
  'placeholder.searchUser': { fr: 'Rechercher un utilisateur...', en: 'Search user...' },
  'placeholder.searchStore': { fr: 'Rechercher une boutique...', en: 'Search store...' },
  'placeholder.searchSupplier': { fr: 'Rechercher un fournisseur...', en: 'Search supplier...' },
  'placeholder.addService': { fr: 'Ajouter un service', en: 'Add a service' },
  'placeholder.addFeature': { fr: 'Ajouter une caractéristique', en: 'Add a feature' },
  'placeholder.imageUrl': { fr: 'URL de l\'image ou importer depuis l\'appareil', en: 'Image URL or import from device' },
  'placeholder.enterCategoryName': { fr: 'Veuillez entrer un nom pour la catégorie', en: 'Please enter a category name' },

  // ==================== CONFIRMATIONS ====================
  'confirm.delete': { fr: 'Êtes-vous sûr de vouloir supprimer ?', en: 'Are you sure you want to delete?' },
  'confirm.deleteUser': { fr: 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?', en: 'Are you sure you want to delete this user?' },
  'confirm.deleteClient': { fr: 'Êtes-vous sûr de vouloir supprimer ce client ?', en: 'Are you sure you want to delete this client?' },
  'confirm.deleteStore': { fr: 'Supprimer la boutique ?', en: 'Delete store?' },
  'confirm.deleteStoreDesc': { fr: 'Cette action est irréversible. La boutique sera définitivement supprimée.', en: 'This action cannot be undone. The store will be permanently deleted.' },
  'confirm.deleteCategory': { fr: 'Supprimer cette catégorie ?', en: 'Delete this category?' },
  'confirm.deleteGroup': { fr: 'Supprimer ce groupe ?', en: 'Delete this group?' },
  'confirm.deleteGroupDesc': { fr: 'Les utilisateurs de ce groupe perdront leurs accès spécifiques.', en: 'Users in this group will lose their specific access.' },
  'confirm.irreversible': { fr: 'Cette action est irréversible.', en: 'This action cannot be undone.' },
  'confirm.areYouSure': { fr: 'Êtes-vous absolument sûr ?', en: 'Are you absolutely sure?' },
  'confirm.resetAllDataDesc': { fr: 'Cette action est irréversible. Toutes les données seront définitivement supprimées, y compris les clients, ventes, articles et paramètres.', en: 'This action cannot be undone. All data will be permanently deleted, including clients, sales, articles and settings.' },
  'confirm.yesDeleteAll': { fr: 'Oui, tout supprimer', en: 'Yes, delete all' },

  // ==================== PERIODS ====================
  'period.thisWeek': { fr: 'Cette semaine', en: 'This week' },
  'period.thisMonth': { fr: 'Ce mois', en: 'This month' },
  'period.thisQuarter': { fr: 'Ce trimestre', en: 'This quarter' },
  'period.thisYear': { fr: 'Cette année', en: 'This year' },

  // ==================== STATUS ====================
  'status.partial': { fr: 'Partiel', en: 'Partial' },
  'status.active': { fr: 'Actif', en: 'Active' },
  'status.inactive': { fr: 'Inactif', en: 'Inactive' },
  'status.completed': { fr: 'Terminé', en: 'Completed' },
  'status.pending': { fr: 'En attente', en: 'Pending' },
  'status.cancelled': { fr: 'Annulé', en: 'Cancelled' },

  // ==================== SUCCESS MESSAGES ====================
  'success.saved': { fr: 'Sauvegardé avec succès!', en: 'Saved successfully!' },
  'success.created': { fr: 'Créé avec succès!', en: 'Created successfully!' },
  'success.updated': { fr: 'Mis à jour avec succès!', en: 'Updated successfully!' },
  'success.deleted': { fr: 'Supprimé avec succès!', en: 'Deleted successfully!' },
  'success.companySettings': { fr: 'Paramètres de l\'entreprise sauvegardés avec succès!', en: 'Company settings saved successfully!' },
  'success.appSettings': { fr: 'Paramètres de l\'application sauvegardés avec succès!', en: 'Application settings saved successfully!' },
  'success.emailSettings': { fr: 'Paramètres email sauvegardés avec succès!', en: 'Email settings saved successfully!' },
  'success.docSettings': { fr: 'Paramètres documents sauvegardés avec succès!', en: 'Document settings saved successfully!' },
  'success.stockSettings': { fr: 'Paramètres stock sauvegardés avec succès!', en: 'Stock settings saved successfully!' },
  'success.securitySettings': { fr: 'Paramètres de sécurité sauvegardés avec succès!', en: 'Security settings saved successfully!' },
  'success.settingsSaved': { fr: 'Paramètres sauvegardés avec succès!', en: 'Settings saved successfully!' },
  'success.cacheCleared': { fr: 'Cache vidé avec succès!', en: 'Cache cleared successfully!' },
  'success.testEmailSent': { fr: 'Test email envoyé!', en: 'Test email sent!' },
  'success.dataImported': { fr: 'Données importées avec succès!', en: 'Data imported successfully!' },

  // ==================== ERROR MESSAGES ====================
  'error.general': { fr: 'Une erreur est survenue', en: 'An error occurred' },
  'error.required': { fr: 'Ce champ est obligatoire', en: 'This field is required' },
  'error.invalidFormat': { fr: 'Format invalide', en: 'Invalid format' },
  'error.noPermission': { fr: 'Vous n\'avez pas la permission d\'effectuer cette action', en: 'You do not have permission to perform this action' },
  'error.noPermissionAdmin': { fr: 'Vous n\'avez pas la permission de créer un administrateur.', en: 'You do not have permission to create an administrator.' },
  'error.noPermissionSuperAdmin': { fr: 'Impossible de créer un Super Administrateur.', en: 'Cannot create a Super Administrator.' },
  'error.validImage': { fr: 'Veuillez sélectionner une image valide', en: 'Please select a valid image' },
  'error.imageSize': { fr: 'L\'image ne doit pas dépasser 5 Mo', en: 'Image must not exceed 5 MB' },
  'error.fileRead': { fr: 'Erreur lors de la lecture du fichier', en: 'Error reading file' },
  'error.validImageDrop': { fr: 'Veuillez déposer une image valide', en: 'Please drop a valid image' },
  'error.invalidFile': { fr: 'Fichier invalide. Veuillez sélectionner un fichier JSON valide.', en: 'Invalid file. Please select a valid JSON file.' },

  // ==================== EMPTY STATES ====================
  'empty.noData': { fr: 'Aucune donnée disponible', en: 'No data available' },
  'empty.noResults': { fr: 'Aucun résultat trouvé', en: 'No results found' },
  'empty.noNotifications': { fr: 'Aucune notification', en: 'No notifications' },
  'empty.noConversations': { fr: 'Aucune conversation', en: 'No conversations' },
  'empty.clientMessagesWillAppear': { fr: 'Les messages des clients apparaîtront ici.', en: 'Client messages will appear here.' },
  'empty.noCategoryData': { fr: 'Aucune donnée de catégorie disponible', en: 'No category data available' },

  // ==================== HOME PAGE ====================
  'home.hero.title': { fr: 'Solutions Électriques Complètes', en: 'Complete Electrical Solutions' },
  'home.hero.subtitle': { fr: 'Du poste source aux usages finaux', en: 'From source to final usage' },
  'home.vision.title': { fr: 'Vision et Mission', en: 'Vision and Mission' },
  'home.vision.content': { fr: 'Leader dans les solutions électriques intégrées, nous fournissons des produits et services de classe mondiale pour les secteurs résidentiel, tertiaire, industriel et énergétique.', en: 'Leader in integrated electrical solutions, we provide world-class products and services for residential, tertiary, industrial and energy sectors.' },
  'home.values.title': { fr: 'Nos Valeurs', en: 'Our Values' },
  'home.values.reliability': { fr: 'Fiabilité', en: 'Reliability' },
  'home.values.innovation': { fr: 'Innovation', en: 'Innovation' },
  'home.values.security': { fr: 'Sécurité', en: 'Security' },
  'home.values.performance': { fr: 'Performance Énergétique', en: 'Energy Performance' },
  'home.standards.title': { fr: 'Normes Internationales', en: 'International Standards' },
  'home.standards.content': { fr: 'Conformes aux normes IEC, ISO et NF - Engagement qualité et excellence', en: 'Compliant with IEC, ISO and NF standards - Quality and excellence commitment' },
  'home.role.title': { fr: 'Notre Rôle dans la Chaîne de l\'Énergie', en: 'Our Role in the Energy Chain' },
  'home.role.content': { fr: 'De la production à la distribution, en passant par le contrôle et l\'automatisation, nous couvrons l\'ensemble des besoins électriques.', en: 'From production to distribution, through control and automation, we cover all electrical needs.' },
  'home.cta.login': { fr: 'Accès Client / Commande', en: 'Client Access / Order' },
  'home.cta.catalog': { fr: 'Voir notre Catalogue', en: 'View our Catalog' },
  'home.leader': { fr: 'Leader en Solutions Électriques', en: 'Leader in Electrical Solutions' },
  'home.yearsOfExperience': { fr: 'Années d\'expérience', en: 'Years of experience' },
  'home.projectsCompleted': { fr: 'Projets réalisés', en: 'Projects completed' },
  'client.area': { fr: 'Espace Client', en: 'Client Area' },

  // ==================== PRODUCTS & SERVICES ====================
  'products.title': { fr: 'Nos Produits', en: 'Our Products' },
  'products.mediumLowVoltage': { fr: 'Moyenne et Basse Tension', en: 'Medium and Low Voltage' },
  'products.renewable': { fr: 'Énergies Renouvelables', en: 'Renewable Energy' },
  'products.automation': { fr: 'Automatismes Industriels', en: 'Industrial Automation' },
  'products.distribution': { fr: 'Distribution et Câblage', en: 'Distribution and Cabling' },
  'services.title': { fr: 'Nos Services', en: 'Our Services' },
  'services.available': { fr: 'Services Disponibles', en: 'Available Services' },

  // ==================== CATALOG ====================
  'catalog.all': { fr: 'Tous', en: 'All' },
  'catalog.search': { fr: 'Rechercher...', en: 'Search...' },
  'catalog.filter': { fr: 'Filtrer', en: 'Filter' },
  'catalog.add': { fr: 'Ajouter', en: 'Add' },
  'catalog.edit': { fr: 'Modifier', en: 'Edit' },
  'catalog.delete': { fr: 'Supprimer', en: 'Delete' },
  'catalog.view': { fr: 'Voir', en: 'View' },
  'catalog.stock': { fr: 'Stock', en: 'Stock' },
  'catalog.price': { fr: 'Prix', en: 'Price' },
  'catalog.manageCategories': { fr: 'Gérer les catégories', en: 'Manage categories' },

  // ==================== ARTICLES ====================
  'articles.title': { fr: 'Articles', en: 'Articles' },
  'articles.subtitle': { fr: 'Gestion du catalogue produits', en: 'Product catalog management' },
  'articles.newArticle': { fr: 'Nouvel Article', en: 'New Article' },
  'articles.editArticle': { fr: 'Modifier l\'Article', en: 'Edit Article' },
  'articles.addArticle': { fr: 'Ajouter un Nouvel Article', en: 'Add New Article' },
  'articles.totalArticles': { fr: 'Total Articles', en: 'Total Articles' },
  'articles.stockValue': { fr: 'Valeur Stock', en: 'Stock Value' },
  'articles.lowStock': { fr: 'Stock Faible', en: 'Low Stock' },
  'articles.createArticle': { fr: 'Créer l\'article', en: 'Create article' },
  'articles.updateArticle': { fr: 'Mettre à jour', en: 'Update' },
  'articles.minStock': { fr: 'Stock minimum', en: 'Minimum stock' },
  'articles.sellingPrice': { fr: 'Prix de vente', en: 'Selling price' },
  'articles.salePrice': { fr: 'Prix de vente', en: 'Sale price' },
  'articles.purchasePrice': { fr: 'Prix d\'achat', en: 'Purchase price' },
  'articles.margin': { fr: 'Marge', en: 'Margin' },
  'articles.stockBelowMinimum': { fr: 'Stock inférieur au seuil minimum ({min})', en: 'Stock below minimum threshold ({min})' },
  'articles.noArticlesFound': { fr: 'Aucun article trouvé', en: 'No articles found' },
  'articles.noArticlesFoundHint': { fr: 'Essayez de modifier vos critères de recherche ou de créer un nouvel article.', en: 'Try adjusting your search criteria or create a new article.' },
  'articles.articleDetails': { fr: 'Détails de l\'Article', en: 'Article Details' },
  'confirm.deleteArticle': { fr: 'Êtes-vous sûr de vouloir supprimer cet article ?', en: 'Are you sure you want to delete this article?' },

  // ==================== SERVICES ====================
  'services.subtitle': { fr: 'Catalogue de services électriques', en: 'Electrical services catalog' },
  'services.newService': { fr: 'Nouveau Service', en: 'New Service' },
  'services.editService': { fr: 'Modifier le Service', en: 'Edit Service' },
  'services.addService': { fr: 'Ajouter un Nouveau Service', en: 'Add New Service' },
  'services.totalServices': { fr: 'Total Services', en: 'Total Services' },
  'services.createService': { fr: 'Créer le service', en: 'Create service' },
  'services.updateService': { fr: 'Mettre à jour', en: 'Update' },
  'services.duration': { fr: 'Durée', en: 'Duration' },
  'services.availableStatus': { fr: 'Disponibles', en: 'Available' },
  'services.requestQuote': { fr: 'Demander un Devis', en: 'Request a Quote' },
  'services.requestQuoteNow': { fr: 'Demander un devis maintenant', en: 'Request a quote now' },
  'services.serviceDetails': { fr: 'Détails du Service', en: 'Service Details' },
  'services.noServicesFound': { fr: 'Aucun service trouvé', en: 'No services found' },
  'services.noServicesFoundHint': { fr: 'Essayez de modifier vos critères de recherche ou d\'ajouter de nouveaux services.', en: 'Try adjusting your search criteria or add new services.' },
  'confirm.deleteService': { fr: 'Êtes-vous sûr de vouloir supprimer ce service ?', en: 'Are you sure you want to delete this service?' },

  // ==================== CLIENTS ====================
  'clients.title': { fr: 'Clients', en: 'Clients' },
  'clients.subtitle': { fr: 'Gestion du portefeuille client', en: 'Client portfolio management' },
  'clients.newClient': { fr: 'Nouveau Client', en: 'New Client' },
  'clients.editClient': { fr: 'Modifier le Client', en: 'Edit Client' },
  'clients.addClient': { fr: 'Ajouter un Nouveau Client', en: 'Add New Client' },
  'clients.totalClients': { fr: 'Total Clients', en: 'Total Clients' },
  'clients.createClient': { fr: 'Ajouter le client', en: 'Add client' },
  'clients.updateClient': { fr: 'Mettre à jour', en: 'Update' },

  // ==================== SALES ====================
  'sales.title': { fr: 'Ventes et Factures', en: 'Sales and Invoices' },
  'sales.subtitle': { fr: 'Gestion des ventes et facturation', en: 'Sales and billing management' },
  'sales.newSale': { fr: 'Nouvelle Vente', en: 'New Sale' },
  'sales.totalSales': { fr: 'Total Ventes', en: 'Total Sales' },
  'sales.salesList': { fr: 'Liste des Ventes', en: 'Sales List' },
  'sales.createInvoice': { fr: 'Créer une facture', en: 'Create invoice' },
  'sales.createQuote': { fr: 'Créer un devis', en: 'Create quote' },
  'sales.invoice': { fr: 'Facture', en: 'Invoice' },
  'sales.quote': { fr: 'Devis', en: 'Quote' },
  'sales.paid': { fr: 'Payé', en: 'Paid' },
  'sales.pending': { fr: 'En attente', en: 'Pending' },
  'sales.cancelled': { fr: 'Annulé', en: 'Cancelled' },
  'sales.catalog': { fr: 'Catalogue', en: 'Catalog' },
  'sales.searchArticleOrService': { fr: 'Rechercher un article ou service...', en: 'Search for an article or service...' },
  'sales.cart': { fr: 'Panier', en: 'Cart' },
  'sales.cartEmpty': { fr: 'Le panier est vide', en: 'Cart is empty' },
  'sales.selectClient': { fr: 'Sélectionner un client', en: 'Select a client' },
  'sales.validateSale': { fr: 'Valider la Vente', en: 'Validate Sale' },
  'sales.createdBy': { fr: 'Effectuée par', en: 'Created by' },

  // ==================== REPORTS ====================
  'reports.title': { fr: 'Rapports et Statistiques', en: 'Reports and Statistics' },
  'reports.subtitle': { fr: 'Vue d\'ensemble des performances', en: 'Performance overview' },
  'reports.totalRevenue': { fr: 'Chiffre d\'Affaires Total', en: 'Total Revenue' },
  'reports.monthlyRevenue': { fr: 'Chiffre d\'Affaires du Mois', en: 'Monthly Revenue' },
  'reports.growth': { fr: 'Croissance', en: 'Growth' },
  'reports.vsPreviousMonth': { fr: 'vs mois précédent', en: 'vs previous month' },
  'reports.paidAmount': { fr: 'Montant Encaissé', en: 'Paid Amount' },
  'reports.ofTotal': { fr: 'du total', en: 'of total' },
  'reports.pendingPayments': { fr: 'En Attente de Paiement', en: 'Pending Payments' },
  'reports.toCollect': { fr: 'à encaisser', en: 'to collect' },
  'reports.stockValue': { fr: 'Valeur du Stock', en: 'Stock Value' },
  'reports.lowStockItems': { fr: 'en stock faible', en: 'low stock' },
  'reports.averageSale': { fr: 'Valeur Moyenne par Vente', en: 'Average Sale Value' },
  'reports.perTransaction': { fr: 'par transaction', en: 'per transaction' },
  'reports.topCategories': { fr: 'Top Catégories par Revenu', en: 'Top Categories by Revenue' },
  'reports.monthlyTrend': { fr: 'Évolution Mensuelle', en: 'Monthly Trend' },
  'reports.quickStats': { fr: 'Statistiques Rapides', en: 'Quick Stats' },
  'reports.totalSales': { fr: 'Ventes Totales', en: 'Total Sales' },
  'reports.transactions': { fr: 'transactions', en: 'transactions' },
  'reports.registeredClients': { fr: 'clients enregistrés', en: 'registered clients' },
  'reports.inCatalog': { fr: 'dans le catalogue', en: 'in catalog' },
  'reports.offered': { fr: 'proposés', en: 'offered' },

  // ==================== SUPPLIERS ====================
  'suppliers.title': { fr: 'Fournisseurs', en: 'Suppliers' },
  'suppliers.subtitle': { fr: 'Gestion des fournisseurs', en: 'Supplier management' },
  'suppliers.newSupplier': { fr: 'Nouveau fournisseur', en: 'New supplier' },
  'suppliers.editSupplier': { fr: 'Modifier le fournisseur', en: 'Edit supplier' },
  'suppliers.totalSuppliers': { fr: 'Total Fournisseurs', en: 'Total Suppliers' },
  'suppliers.activeSuppliers': { fr: 'Fournisseurs Actifs', en: 'Active Suppliers' },
  'suppliers.createSupplier': { fr: 'Créer', en: 'Create' },
  'suppliers.updateSupplier': { fr: 'Mettre à jour', en: 'Update' },
  'supplier.totalPurchases': { fr: 'Total Achats', en: 'Total Purchases' },
  'supplier.orders': { fr: 'Commandes', en: 'Orders' },
  'supplier.noSuppliersFound': { fr: 'Aucun fournisseur trouvé', en: 'No suppliers found' },
  'supplier.editDescription': { fr: 'Modifiez les informations du fournisseur', en: 'Edit supplier information' },
  'supplier.addDescription': { fr: 'Ajoutez un nouveau fournisseur à votre liste', en: 'Add a new supplier to your list' },
  'supplier.companyName': { fr: 'Nom de l\'entreprise', en: 'Company name' },
  'supplier.contactName': { fr: 'Nom du contact', en: 'Contact name' },
  'supplier.website': { fr: 'Site web', en: 'Website' },
  'supplier.paymentTerms': { fr: 'Conditions de paiement', en: 'Payment terms' },
  'supplier.additionalInfo': { fr: 'Informations supplémentaires...', en: 'Additional information...' },
  'supplier.category.electrical': { fr: 'Électrique', en: 'Electrical' },
  'supplier.category.automation': { fr: 'Automatisme', en: 'Automation' },
  'supplier.category.solar': { fr: 'Solaire', en: 'Solar' },
  'supplier.category.cables': { fr: 'Câblage', en: 'Cables' },
  'supplier.category.general': { fr: 'Général', en: 'General' },
  'confirm.deleteSupplier': { fr: 'Êtes-vous sûr de vouloir supprimer ce fournisseur ?', en: 'Are you sure you want to delete this supplier?' },

  // ==================== STORES ====================
  'stores.title': { fr: 'Gestion des Boutiques', en: 'Store Management' },
  'stores.subtitle': { fr: 'Gérez vos points de vente et groupes d\'utilisateurs', en: 'Manage your stores and user groups' },
  'stores.stores': { fr: 'Boutiques', en: 'Stores' },
  'stores.userGroups': { fr: 'Groupes d\'Utilisateurs', en: 'User Groups' },
  'stores.newStore': { fr: 'Nouvelle Boutique', en: 'New Store' },
  'stores.editStore': { fr: 'Modifier la Boutique', en: 'Edit Store' },
  'stores.newGroup': { fr: 'Nouveau Groupe d\'Utilisateurs', en: 'New User Group' },
  'stores.editGroup': { fr: 'Modifier le Groupe', en: 'Edit Group' },
  'stores.allCountries': { fr: 'Tous les pays', en: 'All countries' },
  'stores.editPermissions': { fr: 'Modifier les informations', en: 'Edit information' },
  'stores.storeCount': { fr: '{count} point(s) de vente • {active} actif(s)', en: '{count} store(s) • {active} active' },
  'stores.noStoresFound': { fr: 'Aucune boutique trouvée', en: 'No stores found' },
  'stores.seeLess': { fr: 'Voir moins', en: 'See less' },
  'stores.seeMore': { fr: 'Voir plus de détails', en: 'See more details' },
  'stores.groupsDescription': { fr: 'Gérez les groupes d\'utilisateurs et leurs accès aux boutiques', en: 'Manage user groups and their store access' },
  'stores.allStores': { fr: 'Toutes les boutiques', en: 'All stores' },
  'stores.assignedStores': { fr: 'Boutiques assignées', en: 'Assigned stores' },
  'stores.accessAllStores': { fr: 'Accès à toutes les boutiques', en: 'Access all stores' },
  'stores.companyWideAccess': { fr: 'Groupe avec accès entreprise complet', en: 'Group with full company access' },
  'stores.getDirections': { fr: 'Obtenir l\'itinéraire', en: 'Get directions' },
  'stores.website': { fr: 'Site Web', en: 'Website' },

  // ==================== USERS ====================
  'users.title': { fr: 'Gestion des Utilisateurs', en: 'User Management' },
  'users.subtitle': { fr: 'Administrez les accès et les rôles de la plateforme', en: 'Manage platform access and roles' },
  'users.addUser': { fr: 'Ajouter un utilisateur', en: 'Add user' },
  'users.newUser': { fr: 'Ajouter un nouvel utilisateur', en: 'Add new user' },
  'users.editUser': { fr: 'Modifier l\'utilisateur', en: 'Edit user' },
  'users.createUser': { fr: 'Créer l\'utilisateur', en: 'Create user' },
  'users.passwordMin8': { fr: 'Minimum 8 caractères', en: 'Minimum 8 characters' },
  'users.onlySuperAdminCanCreateAdmin': { fr: 'Seul le Super Administrateur peut créer des Administrateurs', en: 'Only Super Administrator can create Administrators' },
  'users.newUserDesc': { fr: 'Remplissez les informations pour créer un nouveau compte utilisateur.', en: 'Fill in the information to create a new user account.' },
  'users.newUserDescLimited': { fr: 'Vous pouvez créer des utilisateurs avec des rôles limités.', en: 'You can create users with limited roles.' },

  // ==================== SETTINGS ====================
  'settings.title': { fr: 'Paramètres', en: 'Settings' },
  'settings.subtitle': { fr: 'Configuration du système et de l\'entreprise', en: 'System and company configuration' },
  'settings.company': { fr: 'Entreprise', en: 'Company' },
  'settings.application': { fr: 'Application', en: 'Application' },
  'settings.email': { fr: 'Email', en: 'Email' },
  'settings.documents': { fr: 'Documents', en: 'Documents' },
  'settings.stock': { fr: 'Stock', en: 'Stock' },
  'settings.security': { fr: 'Sécurité', en: 'Security' },
  'settings.appearance': { fr: 'Apparence', en: 'Appearance' },
  'settings.alerts': { fr: 'Alertes', en: 'Alerts' },
  'settings.notifications': { fr: 'Notifications et Alertes', en: 'Notifications and Alerts' },
  'settings.backup': { fr: 'Sauvegarde', en: 'Backup' },
  'settings.testConnection': { fr: 'Tester la connexion', en: 'Test connection' },
  'settings.backupAndMaintenance': { fr: 'Sauvegarde et Maintenance', en: 'Backup and Maintenance' },
  'settings.superAdminOnly': { fr: 'Super Admin uniquement', en: 'Super Admin only' },
  'settings.manageBackupsDesc': { fr: 'Gérez les sauvegardes et la maintenance du système', en: 'Manage backups and system maintenance' },
  'settings.exportData': { fr: 'Exporter les données', en: 'Export data' },
  'settings.downloadFullBackup': { fr: 'Télécharger une sauvegarde complète', en: 'Download a complete backup' },
  'settings.importData': { fr: 'Importer des données', en: 'Import data' },
  'settings.restoreFromBackup': { fr: 'Restaurer depuis une sauvegarde', en: 'Restore from a backup' },
  'settings.clearCache': { fr: 'Vider le cache', en: 'Clear cache' },
  'settings.clearCacheDesc': { fr: 'Supprimer les données temporaires et le cache de l\'application', en: 'Delete temporary data and application cache' },
  'settings.dangerZone': { fr: 'Zone de danger', en: 'Danger zone' },
  'settings.dangerZoneDesc': { fr: 'Actions irréversibles - procéder avec prudence', en: 'Irreversible actions - proceed with caution' },
  'settings.resetAllData': { fr: 'Réinitialiser toutes les données', en: 'Reset all data' },
  // Company settings
  'settings.companyInfo': { fr: 'Informations de l\'Entreprise', en: 'Company Information' },
  'settings.companyInfoDesc': { fr: 'Configurez les informations de l\'entreprise', en: 'Configure company information' },
  'settings.companyName': { fr: 'Nom de l\'entreprise', en: 'Company name' },
  'settings.shortName': { fr: 'Nom court / Sigle', en: 'Short name / Acronym' },
  'settings.website': { fr: 'Site Web', en: 'Website' },
  // Application settings
  'settings.appSettings': { fr: 'Paramètres de l\'Application', en: 'Application Settings' },
  'settings.appSettingsDesc': { fr: 'Configurez les paramètres généraux de l\'application', en: 'Configure general application settings' },
  'settings.taxRate': { fr: 'Taux de TVA (%)', en: 'VAT Rate (%)' },
  'settings.taxRateDesc': { fr: 'Taux de TVA appliqué aux ventes (actuellement: {rate}%)', en: 'VAT rate applied to sales (currently: {rate}%)' },
  'settings.currency': { fr: 'Devise', en: 'Currency' },
  'settings.regionalFormat': { fr: 'Format Régional', en: 'Regional Format' },
  'settings.interfaceLanguage': { fr: 'Langue de l\'Interface', en: 'Interface Language' },
  // Appearance settings
  'settings.appearanceDesc': { fr: 'Personnalisez l\'apparence de l\'application', en: 'Customize the application appearance' },
  'settings.theme': { fr: 'Thème', en: 'Theme' },
  'settings.themeSystem': { fr: 'Système', en: 'System' },
  // Document settings
  'settings.docSettings': { fr: 'Paramètres des Documents', en: 'Document Settings' },
  'settings.docSettingsDesc': { fr: 'Configurez la génération de factures, devis et autres documents', en: 'Configure invoice, quote and document generation' },
  'settings.invoicePrefix': { fr: 'Préfixe Facture', en: 'Invoice Prefix' },
  'settings.quotePrefix': { fr: 'Préfixe Devis', en: 'Quote Prefix' },
  'settings.paymentTerms': { fr: 'Conditions de Paiement', en: 'Payment Terms' },
  'settings.autoNumbering': { fr: 'Numérotation automatique', en: 'Auto numbering' },
  'settings.showLogo': { fr: 'Afficher le logo', en: 'Show logo' },
  'settings.showLogoDesc': { fr: 'Inclure le logo de l\'entreprise sur les documents', en: 'Include company logo on documents' },
  'settings.showBankDetails': { fr: 'Afficher les coordonnées bancaires', en: 'Show bank details' },
  'settings.showBankDetailsDesc': { fr: 'Inclure les informations bancaires sur les factures', en: 'Include bank information on invoices' },
  'settings.footerText': { fr: 'Texte de pied de page', en: 'Footer text' },
  'settings.immediatePayment': { fr: 'Paiement immédiat', en: 'Immediate payment' },
  // Email settings
  'settings.emailConfig': { fr: 'Configuration Email', en: 'Email Configuration' },
  'settings.emailConfigDesc': { fr: 'Configurez l\'envoi d\'emails (factures, notifications)', en: 'Configure email sending (invoices, notifications)' },
  'settings.smtpServer': { fr: 'Serveur SMTP', en: 'SMTP Server' },
  'settings.smtpPort': { fr: 'Port SMTP', en: 'SMTP Port' },
  'settings.senderEmail': { fr: 'Email d\'envoi', en: 'Sender email' },
  'settings.senderName': { fr: 'Nom d\'expéditeur', en: 'Sender name' },
  'settings.secureConnection': { fr: 'Connexion sécurisée (SSL/TLS)', en: 'Secure connection (SSL/TLS)' },
  'settings.secureConnectionDesc': { fr: 'Utiliser une connexion chiffrée pour l\'envoi d\'emails', en: 'Use encrypted connection for email sending' },
  // Stock settings
  'settings.stockSettings': { fr: 'Paramètres du Stock', en: 'Stock Settings' },
  'settings.stockSettingsDesc': { fr: 'Configurez la gestion des stocks et alertes', en: 'Configure stock management and alerts' },
  'settings.lowStockThreshold': { fr: 'Seuil de stock faible', en: 'Low stock threshold' },
  'settings.lowStockThresholdDesc': { fr: 'Alerte quand le stock descend en dessous de cette quantité', en: 'Alert when stock falls below this quantity' },
  'settings.defaultCategory': { fr: 'Catégorie par défaut', en: 'Default category' },
  'settings.autoReorder': { fr: 'Réapprovisionnement automatique', en: 'Auto reorder' },
  'settings.autoReorderDesc': { fr: 'Créer automatiquement des commandes fournisseur lors de stock faible', en: 'Automatically create supplier orders on low stock' },
  // Notification settings
  'settings.notificationsDesc': { fr: 'Gérez vos préférences de notifications', en: 'Manage your notification preferences' },
  'settings.lowStockAlert': { fr: 'Alerte Stock Faible', en: 'Low Stock Alert' },
  'settings.lowStockAlertDesc': { fr: 'Recevoir une notification quand un article atteint le seuil minimum', en: 'Receive notification when an article reaches minimum threshold' },
  'settings.newSaleAlert': { fr: 'Nouvelle Vente', en: 'New Sale' },
  'settings.newSaleAlertDesc': { fr: 'Recevoir une notification à chaque nouvelle vente', en: 'Receive notification for each new sale' },
  'settings.newClientAlert': { fr: 'Nouveau Client', en: 'New Client' },
  'settings.newClientAlertDesc': { fr: 'Recevoir une notification à chaque nouveau client enregistré', en: 'Receive notification for each new registered client' },
  'settings.dailyReportAlert': { fr: 'Rapport Quotidien', en: 'Daily Report' },
  'settings.dailyReportAlertDesc': { fr: 'Recevoir un résumé des activités chaque jour', en: 'Receive daily activity summary' },
  'settings.emailNotifications': { fr: 'Notifications par Email', en: 'Email Notifications' },
  'settings.emailNotificationsDesc': { fr: 'Recevoir les alertes par email', en: 'Receive alerts by email' },
  // Security settings
  'settings.securitySettings': { fr: 'Paramètres de Sécurité', en: 'Security Settings' },
  'settings.securitySettingsDesc': { fr: 'Configurez la sécurité du système', en: 'Configure system security' },
  'settings.sessionTimeout': { fr: 'Expiration de session (minutes)', en: 'Session timeout (minutes)' },
  'settings.maxLoginAttempts': { fr: 'Tentatives de connexion max', en: 'Max login attempts' },
  'settings.strongPassword': { fr: 'Mots de passe forts requis', en: 'Strong passwords required' },
  'settings.strongPasswordDesc': { fr: 'Exiger des mots de passe complexes (8+ caractères, majuscules, chiffres)', en: 'Require complex passwords (8+ characters, uppercase, numbers)' },
  'settings.twoFactorAuth': { fr: 'Authentification à deux facteurs', en: 'Two-factor authentication' },
  'settings.twoFactorAuthDesc': { fr: 'Activer la 2FA pour tous les utilisateurs', en: 'Enable 2FA for all users' },
  // Security info
  'settings.securityInfo': { fr: 'Sécurité', en: 'Security' },
  'settings.loggedInAs': { fr: 'Connecté en tant que', en: 'Logged in as' },
  'settings.canEditSettings': { fr: 'Vous avez les permissions pour modifier les paramètres.', en: 'You have permission to modify settings.' },
  'settings.cannotEditSettings': { fr: 'Seuls les administrateurs peuvent modifier certains paramètres.', en: 'Only administrators can modify certain settings.' },
  
  // Sales & POS settings
  'settings.salesPOS': { fr: 'Ventes & Point de Vente', en: 'Sales & POS' },
  'settings.salesPOSDesc': { fr: 'Configurez les paramètres de vente et du point de vente', en: 'Configure sales and point of sale settings' },
  'settings.posSettings': { fr: 'Paramètres du Point de Vente', en: 'POS Settings' },
  'settings.enablePOS': { fr: 'Mode Point de Vente', en: 'POS Mode' },
  'settings.enablePOSDesc': { fr: 'Activer l\'interface simplifiée pour les ventes rapides', en: 'Enable simplified interface for quick sales' },
  'settings.printReceipt': { fr: 'Impression automatique', en: 'Auto print receipt' },
  'settings.printReceiptDesc': { fr: 'Imprimer automatiquement le ticket après chaque vente', en: 'Automatically print receipt after each sale' },
  'settings.receiptSize': { fr: 'Taille du ticket', en: 'Receipt size' },
  'settings.small': { fr: 'Petit', en: 'Small' },
  'settings.standard': { fr: 'Standard', en: 'Standard' },
  'settings.fullPage': { fr: 'Page entière', en: 'Full page' },
  'settings.defaultPayment': { fr: 'Mode de paiement par défaut', en: 'Default payment method' },
  'settings.discountSettings': { fr: 'Paramètres de Remise', en: 'Discount Settings' },
  'settings.enableDiscounts': { fr: 'Autoriser les remises', en: 'Enable discounts' },
  'settings.enableDiscountsDesc': { fr: 'Permettre aux utilisateurs d\'appliquer des remises sur les ventes', en: 'Allow users to apply discounts on sales' },
  'settings.maxDiscount': { fr: 'Remise maximum', en: 'Maximum discount' },
  'settings.requireApproval': { fr: 'Approbation manager', en: 'Manager approval' },
  'settings.requireApprovalDesc': { fr: 'Exiger l\'approbation du manager pour les remises importantes', en: 'Require manager approval for large discounts' },
  'settings.approvalThreshold': { fr: 'Seuil d\'approbation', en: 'Approval threshold' },
  'settings.layawaySettings': { fr: 'Paramètres de Mise de Côté', en: 'Layaway Settings' },
  'settings.enableLayaway': { fr: 'Activer la mise de côté', en: 'Enable layaway' },
  'settings.enableLayawayDesc': { fr: 'Permettre aux clients de réserver des articles avec un acompte', en: 'Allow customers to reserve items with a deposit' },
  'settings.minDeposit': { fr: 'Acompte minimum', en: 'Minimum deposit' },
  'settings.otherOptions': { fr: 'Autres Options', en: 'Other Options' },
  'settings.multiPayment': { fr: 'Paiement multiple', en: 'Multi-payment' },
  'settings.enableTips': { fr: 'Activer les pourboires', en: 'Enable tips' },
  'settings.priceWithTax': { fr: 'Afficher prix TTC', en: 'Show price with tax' },
  
  // Regional settings
  'settings.regional': { fr: 'Paramètres Régionaux', en: 'Regional Settings' },
  'settings.regionalDesc': { fr: 'Configurez les formats de date, heure et nombre', en: 'Configure date, time and number formats' },
  'settings.timezone': { fr: 'Fuseau horaire', en: 'Timezone' },
  'settings.dateFormat': { fr: 'Format de date', en: 'Date format' },
  'settings.timeFormat': { fr: 'Format d\'heure', en: 'Time format' },
  'settings.numberFormat': { fr: 'Format des nombres', en: 'Number format' },
  'settings.weekStart': { fr: 'Début de la semaine', en: 'Week starts on' },
  'settings.fiscalYearStart': { fr: 'Début de l\'année fiscale', en: 'Fiscal year start' },
  
  // Integration settings
  'settings.integrations': { fr: 'Intégrations', en: 'Integrations' },
  'settings.integrationsDesc': { fr: 'Gérez les connexions avec des services externes', en: 'Manage connections with external services' },
  'settings.apiSettings': { fr: 'Paramètres API', en: 'API Settings' },
  'settings.enableAPI': { fr: 'Activer l\'API', en: 'Enable API' },
  'settings.enableAPIDesc': { fr: 'Permettre l\'accès aux données via API REST', en: 'Allow data access via REST API' },
  'settings.apiKey': { fr: 'Clé API', en: 'API Key' },
  'settings.webhookUrl': { fr: 'URL Webhook', en: 'Webhook URL' },
  'settings.enableWhatsApp': { fr: 'WhatsApp Business', en: 'WhatsApp Business' },
  'settings.enableWhatsAppDesc': { fr: 'Envoyer des notifications et factures via WhatsApp', en: 'Send notifications and invoices via WhatsApp' },
  'settings.whatsAppNumber': { fr: 'Numéro WhatsApp', en: 'WhatsApp number' },
  'settings.enableSMS': { fr: 'Notifications SMS', en: 'SMS Notifications' },
  'settings.enableSMSDesc': { fr: 'Envoyer des SMS aux clients pour les alertes', en: 'Send SMS to clients for alerts' },
  'settings.smsProvider': { fr: 'Fournisseur SMS', en: 'SMS Provider' },
  'settings.paymentGateway': { fr: 'Passerelle de Paiement', en: 'Payment Gateway' },
  'settings.enablePaymentGateway': { fr: 'Paiement en ligne', en: 'Online payment' },
  'settings.enablePaymentGatewayDesc': { fr: 'Accepter les paiements par carte et mobile money', en: 'Accept card and mobile money payments' },
  'settings.selectGateway': { fr: 'Sélectionner la passerelle', en: 'Select gateway' },
  
  // Payment methods
  'payment.cash': { fr: 'Espèces', en: 'Cash' },
  'payment.card': { fr: 'Carte bancaire', en: 'Card' },
  'payment.mobile': { fr: 'Mobile Money', en: 'Mobile Money' },
  'payment.transfer': { fr: 'Virement', en: 'Bank Transfer' },
  
  // Days and months
  'days.monday': { fr: 'Lundi', en: 'Monday' },
  'days.sunday': { fr: 'Dimanche', en: 'Sunday' },
  'days.saturday': { fr: 'Samedi', en: 'Saturday' },
  'months.january': { fr: 'Janvier', en: 'January' },
  'months.april': { fr: 'Avril', en: 'April' },
  'months.july': { fr: 'Juillet', en: 'July' },
  'months.october': { fr: 'Octobre', en: 'October' },

  // ==================== ACCOUNTING ====================
  'accounting.title': { fr: 'Comptabilité', en: 'Accounting' },
  'accounting.subtitle': { fr: 'Gestion comptable', en: 'Accounting management' },
  'accounting.income': { fr: 'Recettes', en: 'Income' },
  'accounting.expenses': { fr: 'Dépenses', en: 'Expenses' },
  'accounting.balance': { fr: 'Solde', en: 'Balance' },
  'accounting.netProfit': { fr: 'Bénéfice Net', en: 'Net Profit' },
  'accounting.margin': { fr: 'Marge', en: 'Margin' },
  'accounting.vatToPay': { fr: 'TVA à Payer', en: 'VAT to Pay' },
  'accounting.newEntry': { fr: 'Nouvelle écriture', en: 'New entry' },
  'accounting.sendReport': { fr: 'Envoyer rapport', en: 'Send report' },
  'accounting.productSales': { fr: 'Ventes Produits', en: 'Product Sales' },
  'accounting.serviceSales': { fr: 'Ventes Services', en: 'Service Sales' },
  'accounting.miscIncome': { fr: 'Revenus Divers', en: 'Miscellaneous Income' },
  'accounting.refundsReceived': { fr: 'Remboursements Reçus', en: 'Refunds Received' },
  'accounting.subsidies': { fr: 'Subventions', en: 'Subsidies' },
  'accounting.purchases': { fr: 'Achats Marchandises', en: 'Merchandise Purchases' },
  'accounting.salaries': { fr: 'Salaires et Charges', en: 'Salaries and Charges' },
  'accounting.rent': { fr: 'Loyer et Charges', en: 'Rent and Charges' },
  'accounting.utilities': { fr: 'Électricité et Eau', en: 'Electricity and Water' },
  'accounting.transport': { fr: 'Transport et Déplacement', en: 'Transport and Travel' },
  'accounting.officeSupplies': { fr: 'Fournitures Bureau', en: 'Office Supplies' },
  'accounting.marketing': { fr: 'Marketing et Publicité', en: 'Marketing and Advertising' },
  'accounting.maintenance': { fr: 'Maintenance et Réparations', en: 'Maintenance and Repairs' },
  'accounting.taxes': { fr: 'Impôts et Taxes', en: 'Taxes' },
  'accounting.financialRatios': { fr: 'Ratios Financiers et Interprétation', en: 'Financial Ratios and Interpretation' },
  // Accounting view specific
  'accounting.overview': { fr: 'Vue d\'ensemble', en: 'Overview' },
  'accounting.entries': { fr: 'Écritures', en: 'Entries' },
  'accounting.reports': { fr: 'Rapports', en: 'Reports' },
  'accounting.analysis': { fr: 'Analyse', en: 'Analysis' },
  'accounting.treasury': { fr: 'Trésorerie', en: 'Treasury' },
  'accounting.salesReceived': { fr: 'Ventes encaissées', en: 'Sales received' },
  'accounting.pendingPayments': { fr: 'Paiements en attente', en: 'Pending payments' },
  'accounting.stockValue': { fr: 'Valeur du stock', en: 'Stock value' },
  'accounting.pendingEntries': { fr: 'Écritures en attente', en: 'Pending entries' },
  'accounting.vatCollected': { fr: 'TVA Collectée (ventes)', en: 'VAT Collected (sales)' },
  'accounting.vatDeductible': { fr: 'TVA Déductible (achats)', en: 'VAT Deductible (purchases)' },
  'accounting.netVatToPay': { fr: 'TVA Nette à Payer', en: 'Net VAT to Pay' },
  'accounting.vatCredit': { fr: 'crédit', en: 'credit' },
  'accounting.expensesByCategory': { fr: 'Dépenses par Catégorie', en: 'Expenses by Category' },
  'accounting.incomeByCategory': { fr: 'Recettes par Catégorie', en: 'Income by Category' },
  'accounting.noExpensesRecorded': { fr: 'Aucune dépense enregistrée', en: 'No expenses recorded' },
  'accounting.noIncomeRecorded': { fr: 'Aucune recette enregistrée', en: 'No income recorded' },
  'accounting.accountingEntries': { fr: 'Écritures Comptables', en: 'Accounting Entries' },
  'accounting.date': { fr: 'Date', en: 'Date' },
  'accounting.type': { fr: 'Type', en: 'Type' },
  'accounting.category': { fr: 'Catégorie', en: 'Category' },
  'accounting.description': { fr: 'Description', en: 'Description' },
  'accounting.amount': { fr: 'Montant', en: 'Amount' },
  'accounting.status': { fr: 'Statut', en: 'Status' },
  'accounting.expense': { fr: 'Dépense', en: 'Expense' },
  'accounting.receipt': { fr: 'Recette', en: 'Receipt' },
  'accounting.pending': { fr: 'En attente', en: 'Pending' },
  'accounting.validated': { fr: 'Validé', en: 'Validated' },
  'accounting.rejected': { fr: 'Rejeté', en: 'Rejected' },
  'accounting.noEntriesForPeriod': { fr: 'Aucune écriture pour cette période', en: 'No entries for this period' },
  'accounting.sentReports': { fr: 'Rapports Envoyés', en: 'Sent Reports' },
  'accounting.sendAReport': { fr: 'Envoyer un rapport', en: 'Send a report' },
  'accounting.noReportsSent': { fr: 'Aucun rapport envoyé', en: 'No reports sent' },
  'accounting.approved': { fr: 'Approuvé', en: 'Approved' },
  'accounting.sent': { fr: 'Envoyé', en: 'Sent' },
  'accounting.draft': { fr: 'Brouillon', en: 'Draft' },
  'accounting.sentTo': { fr: 'Envoyé à', en: 'Sent to' },
  'accounting.simplifiedIncomeStatement': { fr: 'Compte de Résultat Simplifié', en: 'Simplified Income Statement' },
  'accounting.performanceAnalysis': { fr: 'Analyse de la performance économique de l\'entreprise', en: 'Analysis of the company\'s economic performance' },
  'accounting.operatingIncome': { fr: 'PRODUITS D\'EXPLOITATION', en: 'OPERATING INCOME' },
  'accounting.turnover': { fr: 'Chiffre d\'affaires (ventes de marchandises)', en: 'Turnover (merchandise sales)' },
  'accounting.otherOperatingIncome': { fr: 'Autres produits d\'exploitation', en: 'Other operating income' },
  'accounting.totalProducts': { fr: 'Total Produits', en: 'Total Income' },
  'accounting.operatingExpenses': { fr: 'CHARGES D\'EXPLOITATION', en: 'OPERATING EXPENSES' },
  'accounting.otherCharges': { fr: 'Autres charges...', en: 'Other charges...' },
  'accounting.totalCharges': { fr: 'Total Charges', en: 'Total Charges' },
  'accounting.operatingResult': { fr: 'RÉSULTAT D\'EXPLOITATION', en: 'OPERATING RESULT' },
  'accounting.productsMinusCharges': { fr: 'Produits - Charges = Résultat Net', en: 'Income - Expenses = Net Result' },
  'accounting.netProfitMargin': { fr: 'Marge Bénéficiaire Nette', en: 'Net Profit Margin' },
  'accounting.coverageRatio': { fr: 'Ratio de Couverture des Charges', en: 'Expense Coverage Ratio' },
  'accounting.collectionRate': { fr: 'Taux de Recouvrement', en: 'Collection Rate' },
  'accounting.vatAnalysis': { fr: 'Analyse de la TVA', en: 'VAT Analysis' },
  'accounting.vatMechanism': { fr: 'Mécanisme de la TVA', en: 'VAT Mechanism' },
  'accounting.vatToRemit': { fr: 'TVA à Reverser', en: 'VAT to Remit' },
  'accounting.vatCreditTitle': { fr: 'Crédit de TVA', en: 'VAT Credit' },
  'accounting.accountantRecommendations': { fr: 'Recommandations du Comptable', en: 'Accountant Recommendations' },
  'accounting.globalFinancialSituation': { fr: 'Situation Financière Globale', en: 'Global Financial Situation' },
  'accounting.treasuryManagement': { fr: 'Gestion de la Trésorerie', en: 'Treasury Management' },
  'accounting.stockValueTitle': { fr: 'Valeur du Stock', en: 'Stock Value' },
  'accounting.fiscalObligations': { fr: 'Obligations Fiscales', en: 'Fiscal Obligations' },
  'accounting.priorityActions': { fr: 'Actions Prioritaires', en: 'Priority Actions' },
  'accounting.periodSummary': { fr: 'Synthèse de la Période', en: 'Period Summary' },
  'accounting.newAccountingEntry': { fr: 'Nouvelle Écriture Comptable', en: 'New Accounting Entry' },
  'accounting.addIncomeOrExpense': { fr: 'Ajoutez une nouvelle recette ou dépense', en: 'Add a new income or expense' },
  'accounting.selectCategory': { fr: 'Sélectionner une catégorie', en: 'Select a category' },
  'accounting.operationDescription': { fr: 'Description de l\'opération', en: 'Operation description' },
  'accounting.referenceOptional': { fr: 'Référence (optionnel)', en: 'Reference (optional)' },
  'accounting.invoiceNumber': { fr: 'N° facture, bon, etc.', en: 'Invoice number, receipt, etc.' },
  'accounting.notesOptional': { fr: 'Notes (optionnel)', en: 'Notes (optional)' },
  'accounting.additionalNotes': { fr: 'Notes additionnelles', en: 'Additional notes' },
  'accounting.sendTheReport': { fr: 'Envoyer le Rapport', en: 'Send the Report' },
  'accounting.reportWillBeSent': { fr: 'Ce rapport sera envoyé au Superadmin, Admin et Manager', en: 'This report will be sent to Superadmin, Admin and Manager' },
  'accounting.reportTitle': { fr: 'Titre du rapport', en: 'Report title' },
  'accounting.reportTitlePlaceholder': { fr: 'Ex: Rapport mensuel Janvier 2026', en: 'Ex: Monthly report January 2026' },
  'accounting.reportSummary': { fr: 'Résumé du rapport', en: 'Report summary' },
  'accounting.period': { fr: 'Période', en: 'Period' },
  'accounting.willBeSentTo': { fr: 'Sera envoyé à', en: 'Will be sent to' },
  'accounting.importData': { fr: 'Importer des données', en: 'Import data' },
  'accounting.entriesDetected': { fr: 'écritures détectées dans le fichier', en: 'entries detected in the file' },
  'accounting.importEntries': { fr: 'Importer {count} écritures', en: 'Import {count} entries' },

  // ==================== CATEGORIES ====================
  'categories.title': { fr: 'Gestion des Catégories', en: 'Category Management' },
  'categories.description': { fr: 'Organisez vos produits et services par catégories', en: 'Organize your products and services by categories' },
  'categories.newCategory': { fr: 'Nouvelle Catégorie', en: 'New Category' },
  'categories.editCategory': { fr: 'Modifier la Catégorie', en: 'Edit Category' },
  'categories.articles': { fr: 'Articles', en: 'Articles' },
  'categories.services': { fr: 'Services', en: 'Services' },
  'categories.cablingConnectors': { fr: 'Câblage et Connectique', en: 'Cables and Wiring' },
  'categories.measurementMetering': { fr: 'Mesure et Comptage', en: 'Measurement and Metering' },
  'categories.manage': { fr: 'Gérer les catégories', en: 'Manage categories' },
  'categories.allCategories': { fr: 'Toutes catégories', en: 'All categories' },
  'categories.noArticleCategories': { fr: 'Aucune catégorie d\'articles', en: 'No article categories' },
  'categories.noServiceCategories': { fr: 'Aucune catégorie de services', en: 'No service categories' },
  'categories.categoryName': { fr: 'Nom de la catégorie', en: 'Category name' },
  'categories.categoryNamePlaceholder': { fr: 'Ex: Protection Électrique', en: 'Ex: Electrical Protection' },
  'categories.categoryNameEn': { fr: 'Nom en anglais', en: 'English name' },
  'categories.categoryNameEnPlaceholder': { fr: 'Ex: Electrical Protection', en: 'Ex: Electrical Protection' },
  'categories.parentCategory': { fr: 'Catégorie parente (optionnel)', en: 'Parent category (optional)' },
  'categories.noParent': { fr: 'Aucune (catégorie principale)', en: 'None (main category)' },
  'categories.deleteSubcategoriesWarning': { fr: 'Cette action est irréversible. Les sous-catégories seront également supprimées.', en: 'This action cannot be undone. Subcategories will also be deleted.' },

  // ==================== COLORS ====================
  'color.blue': { fr: 'Bleu', en: 'Blue' },
  'color.purple': { fr: 'Violet', en: 'Purple' },
  'color.pink': { fr: 'Rose', en: 'Pink' },
  'color.red': { fr: 'Rouge', en: 'Red' },
  'color.orange': { fr: 'Orange', en: 'Orange' },
  'color.green': { fr: 'Vert', en: 'Green' },
  'color.cyan': { fr: 'Cyan', en: 'Cyan' },
  'color.gray': { fr: 'Gris', en: 'Gray' },
  'color.black': { fr: 'Noir', en: 'Black' },

  // ==================== DASHBOARD ====================
  'dashboard.welcome': { fr: 'Bienvenue', en: 'Welcome' },
  'dashboard.stats': { fr: 'Statistiques', en: 'Statistics' },
  'dashboard.sales': { fr: 'Ventes', en: 'Sales' },
  'dashboard.revenue': { fr: 'Revenus', en: 'Revenue' },
  'dashboard.alerts': { fr: 'Alertes', en: 'Alerts' },
  'dashboard.recent': { fr: 'Activité Récente', en: 'Recent Activity' },
  'dashboard.quickActions': { fr: 'Actions Rapides', en: 'Quick Actions' },

  // ==================== ROLES ====================
  'role.superadmin': { fr: 'Super Administrateur', en: 'Super Administrator' },
  'role.admin': { fr: 'Administrateur', en: 'Administrator' },
  'role.secretaire': { fr: 'Secrétaire', en: 'Secretary' },
  'role.manager': { fr: 'Manager', en: 'Manager' },
  'role.comptable': { fr: 'Comptable', en: 'Accountant' },
  'role.client': { fr: 'Client', en: 'Client' },
  'role.commercial': { fr: 'Commercial', en: 'Sales Rep' },
  'role.clientLimited': { fr: 'Client (Accès Limité)', en: 'Client (Limited Access)' },

  // ==================== VISITOR ANALYTICS ====================
  'analytics.visitors.title': { fr: 'Analyse des Visiteurs', en: 'Visitor Analytics' },
  'analytics.visitors.subtitle': { fr: 'Statistiques et tendances pour l\'étude de marché', en: 'Statistics and trends for market research' },
  'analytics.total': { fr: 'Total Visiteurs', en: 'Total Visitors' },
  'analytics.growth': { fr: 'vs semaine dernière', en: 'vs last week' },
  'analytics.topCity': { fr: 'Ville Principale', en: 'Top City' },
  'analytics.peakHour': { fr: 'Heure de Pointe', en: 'Peak Hour' },
  'analytics.visitors.count': { fr: 'visiteurs', en: 'visitors' },
  'analytics.mobileVsDesktop': { fr: 'Mobile vs Desktop', en: 'Mobile vs Desktop' },
  'analytics.mobile': { fr: 'mobile', en: 'mobile' },
  'analytics.desktop': { fr: 'desktop', en: 'desktop' },
  'analytics.cityDistribution': { fr: 'Distribution par Ville', en: 'Distribution by City' },
  'analytics.deviceDistribution': { fr: 'Répartition par Appareil', en: 'Device Distribution' },
  'analytics.hourlyActivity': { fr: 'Activité par Heure', en: 'Hourly Activity' },
  'analytics.dateTrend': { fr: 'Tendance par Date', en: 'Date Trend' },
  'analytics.device.mobile': { fr: 'Mobile', en: 'Mobile' },
  'analytics.device.desktop': { fr: 'Desktop', en: 'Desktop' },
  'analytics.device.unknown': { fr: 'Inconnu', en: 'Unknown' },

  // ==================== CHAT ====================
  'chat.title': { fr: 'Chat', en: 'Chat' },
  'chat.clientMessages': { fr: 'Messages Clients', en: 'Client Messages' },
  'chat.conversation': { fr: 'Conversation avec le client', en: 'Conversation with client' },
  'chat.replyToClients': { fr: 'Répondez aux demandes des clients', en: 'Reply to client requests' },
  'chat.contactSupport': { fr: 'Contacter le support', en: 'Contact support' },
  'chat.closeChat': { fr: 'Fermer le chat', en: 'Close chat' },
  'chat.unreadMessages': { fr: 'messages non lus', en: 'unread messages' },
  'chat.sendMessage': { fr: 'Envoyer un message', en: 'Send message' },
  'chat.typeMessage': { fr: 'Tapez votre message...', en: 'Type your message...' },

  // ==================== STOCK ====================
  'stock.title': { fr: 'Gestion du Stock', en: 'Stock Management' },
  'stock.subtitle': { fr: 'Suivi en temps réel de l\'inventaire', en: 'Real-time inventory tracking' },
  'stock.totalUnits': { fr: 'Total Unités', en: 'Total Units' },
  'stock.stockValue': { fr: 'Valeur Stock', en: 'Stock Value' },
  'stock.stockAlerts': { fr: 'Alertes Stock', en: 'Stock Alerts' },
  'stock.movements': { fr: 'Mouvements de Stock', en: 'Stock Movements' },
  'stock.entry': { fr: 'Entrée', en: 'Entry' },
  'stock.exit': { fr: 'Sortie', en: 'Exit' },
  'stock.currentStock': { fr: 'Stock Actuel', en: 'Current Stock' },
  'stock.minThreshold': { fr: 'Seuil Min', en: 'Min Threshold' },
  'stock.critical': { fr: 'Critique', en: 'Critical' },
  'stock.low': { fr: 'Faible', en: 'Low' },
  'stock.normal': { fr: 'Normal', en: 'Normal' },
  'stock.transfer': { fr: 'Transfert', en: 'Transfer' },
  'stock.transferDescription': { fr: 'Transférer du stock d\'une boutique à une autre', en: 'Transfer stock from one store to another' },
  'stock.selectArticle': { fr: 'Sélectionner un article', en: 'Select an article' },
  'stock.fromStore': { fr: 'Boutique Source', en: 'From Store' },
  'stock.toStore': { fr: 'Boutique Destination', en: 'To Store' },
  'stock.selectStore': { fr: 'Sélectionner une boutique', en: 'Select a store' },
  'stock.confirmTransfer': { fr: 'Confirmer le Transfert', en: 'Confirm Transfer' },
  'stock.units': { fr: 'unités', en: 'units' },
  'stock.autoReorder': { fr: 'Réapprovisionner', en: 'Auto Reorder' },
  'stock.autoReorderTitle': { fr: 'Réapprovisionnement Automatique', en: 'Auto Reorder' },
  'stock.autoReorderDescription': { fr: 'Créer des commandes fournisseurs pour les articles en rupture de stock', en: 'Create supplier orders for low stock items' },
  'stock.noReorderNeeded': { fr: 'Aucun réapprovisionnement nécessaire', en: 'No reorder needed' },
  'stock.current': { fr: 'Actuel', en: 'Current' },
  'stock.min': { fr: 'Min', en: 'Min' },
  'stock.totalItems': { fr: 'Total articles', en: 'Total items' },
  'stock.estimatedCost': { fr: 'Coût estimé', en: 'Estimated cost' },
  'stock.createSupplierOrder': { fr: 'Créer commande fournisseur', en: 'Create Supplier Order' },
  'stock.reorderCreated': { fr: 'Commande créée', en: 'Order Created' },
  'stock.reorderCreatedMessage': { fr: 'Commande fournisseur créée avec succès', en: 'Supplier order created successfully' },
  'stock.reorderError': { fr: 'Erreur de réapprovisionnement', en: 'Reorder Error' },
  'stock.reorderErrorMessage': { fr: 'Impossible de vérifier les besoins de réapprovisionnement', en: 'Unable to check reorder needs' },
  'stock.reorderProcessError': { fr: 'Erreur lors de la création de la commande', en: 'Error creating order' },

  // ==================== STORE ACCESS ====================
  'store.selectStore': { fr: 'Sélectionner une boutique', en: 'Select a store' },
  'store.noStore': { fr: 'Aucune boutique', en: 'No store' },
  'store.allStores': { fr: 'Toutes les boutiques', en: 'All Stores' },
  'store.viewAllData': { fr: 'Voir toutes les données', en: 'View all data' },
  'store.globalAccess': { fr: 'Accès global', en: 'Global Access' },
  'store.stores': { fr: 'boutiques', en: 'stores' },
  'store.all': { fr: 'Toutes', en: 'All' },
  'store.singleStore': { fr: 'Une boutique', en: 'Single Store' },
  'store.multipleStores': { fr: 'Plusieurs boutiques', en: 'Multiple Stores' },
  'store.assignStores': { fr: 'Attribuer des boutiques', en: 'Assign Stores' },
  'store.accessType': { fr: 'Type d\'accès', en: 'Access Type' },
  'store.permissions': { fr: 'Permissions', en: 'Permissions' },
  'store.canCreate': { fr: 'Peut créer', en: 'Can create' },
  'store.canEdit': { fr: 'Peut modifier', en: 'Can edit' },
  'store.canDelete': { fr: 'Peut supprimer', en: 'Can delete' },
  'store.canViewReports': { fr: 'Peut voir les rapports', en: 'Can view reports' },
  'store.canManageStock': { fr: 'Peut gérer le stock', en: 'Can manage stock' },
  'store.canManageUsers': { fr: 'Peut gérer les utilisateurs', en: 'Can manage users' },
  'store.assignedStores': { fr: 'Boutiques attribuées', en: 'Assigned Stores' },
  'store.noAssignedStores': { fr: 'Aucune boutique attribuée', en: 'No assigned stores' },
  'store.addStore': { fr: 'Ajouter une boutique', en: 'Add a store' },
  'store.removeStore': { fr: 'Retirer la boutique', en: 'Remove store' },
  'store.accessProfile': { fr: 'Profil d\'accès', en: 'Access Profile' },
  'store.filterByStore': { fr: 'Filtrer par boutique', en: 'Filter by store' },

  // ==================== DASHBOARD (continued) ====================
  'dashboard.recentTransactions': { fr: 'Transactions Récentes', en: 'Recent Transactions' },
  'dashboard.newInvoice': { fr: 'Nouvelle Facture', en: 'New Invoice' },
  'dashboard.addClient': { fr: 'Ajouter Client', en: 'Add Client' },
  'dashboard.newProduct': { fr: 'Nouveau Produit', en: 'New Product' },
  'dashboard.sendEmail': { fr: 'Envoyer Email', en: 'Send Email' },
  'dashboard.vsLastMonth': { fr: 'vs mois dernier', en: 'vs last month' },
  'dashboard.emailSimulation': { fr: 'Envoyer un Email (Simulation)', en: 'Send Email (Simulation)' },
  'dashboard.recipient': { fr: 'Destinataire', en: 'Recipient' },
  'dashboard.subject': { fr: 'Sujet', en: 'Subject' },
  'dashboard.message': { fr: 'Message', en: 'Message' },
  'dashboard.yourMessage': { fr: 'Votre message...', en: 'Your message...' },
  'dashboard.emailSent': { fr: 'Email envoyé (simulation)', en: 'Email sent (simulation)' },

  // ==================== NOTIFICATIONS ====================
  'notifications.title': { fr: 'Notifications', en: 'Notifications' },
  'notifications.unread': { fr: 'non lues', en: 'unread' },
  'notifications.markAllRead': { fr: 'Tout marquer comme lu', en: 'Mark all as read' },
  'notifications.deleteAll': { fr: 'Tout supprimer', en: 'Delete all' },
  'notifications.noNotifications': { fr: 'Aucune notification', en: 'No notifications' },
  'notifications.justNow': { fr: 'À l\'instant', en: 'Just now' },
  'notifications.minutesAgo': { fr: 'il y a {count} min', en: '{count} min ago' },
  'notifications.hoursAgo': { fr: 'il y a {count}h', en: '{count}h ago' },
  'notifications.daysAgo': { fr: 'il y a {count}j', en: '{count}d ago' },

  // ==================== IMAGE UPLOAD ====================
  'imageUpload.title': { fr: 'Ajouter une image', en: 'Add image' },
  'imageUpload.description': { fr: 'Importez une image depuis votre appareil ou utilisez une URL', en: 'Import an image from your device or use a URL' },
  'imageUpload.clickToAdd': { fr: 'Cliquez pour ajouter', en: 'Click to add' },
  'imageUpload.dropHere': { fr: 'Cliquez ou glissez une image ici', en: 'Click or drop an image here' },
  'imageUpload.browse': { fr: 'Parcourir', en: 'Browse' },
  'imageUpload.imageUrl': { fr: 'URL de l\'image', en: 'Image URL' },
  'imageUpload.preview': { fr: 'Aperçu', en: 'Preview' },
  'imageUpload.imported': { fr: 'Image importée', en: 'Imported image' },
  'error.invalidImage': { fr: 'Image non valide ou inaccessible', en: 'Invalid or inaccessible image' },

  // ==================== THEME ====================
  'theme.light': { fr: 'Clair', en: 'Light' },
  'theme.dark': { fr: 'Sombre', en: 'Dark' },
  'theme.toggle': { fr: 'Basculer le thème', en: 'Toggle theme' },

  // ==================== LANGUAGE ====================
  'language.french': { fr: 'Français', en: 'French' },
  'language.english': { fr: 'Anglais', en: 'English' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('sps_language');
      if (saved === 'fr' || saved === 'en') return saved;
    }
    return 'fr';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('sps_language', lang);
    }
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[key]?.[language] || key;
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(value));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
